import type { MediaAsset } from '@/content/schema';

export const CLOUD_NAME = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME ?? '';

export function isCloudinaryConfigured(): boolean {
  return CLOUD_NAME.length > 0;
}

/**
 * `next/image` loader for Cloudinary.
 *
 * `f_auto` and `q_auto` let Cloudinary pick format and quality per browser, so
 * the delivered bytes are AVIF/WebP where supported without us managing
 * variants. Transformations happen on Cloudinary's CDN, not our server — which
 * is the point of using it rather than Next's own optimiser.
 */
export function cloudinaryLoader({
  src,
  width,
  quality,
}: {
  src: string;
  width: number;
  quality?: number;
}): string {
  const transforms = [
    'f_auto',
    `q_${quality ?? 'auto'}`,
    `w_${width}`,
    'c_limit',
  ].join(',');

  return `https://res.cloudinary.com/${CLOUD_NAME}/image/upload/${transforms}/${src}`;
}

/** A tiny blurred placeholder, generated by Cloudinary from the same asset. */
export function blurUrl(publicId: string): string {
  return `https://res.cloudinary.com/${CLOUD_NAME}/image/upload/f_auto,q_auto,w_24,e_blur:200/${publicId}`;
}

export function assetUrl(asset: MediaAsset, width = 1600): string {
  return cloudinaryLoader({ src: asset.publicId, width });
}
